Postgres built through docker
zero-to-mastery/drum-root-api pull request #7
Opened 2019-11-16 06:10 UTC by aneesh4995

2019-11-16 06:12 UTC, aneesh4995 commented
done with dockerizing postgres @rgavinc @yashShelatkar

2019-11-16 23:34 UTC, rgavinc requested changes
Looking good, I'm just not sure that the readme correctly covers how to access the DB.

2019-11-16 23:34 UTC, rgavinc commented on README.md
> +    docker exec -it 05b3a3471f6f bash
This command isn't working for me after running `docker-compose up --build`,  I get:
`No such container: 05b3a3471f6f`
- [ ] Make sure that is the correct command.

2019-11-17 00:07 UTC, aneesh4995 commented
Done with the changes. Please test and revert any updations required @rgavinc

2019-11-17 00:33 UTC, rgavinc approved these changes
Awesome work!

2019-11-20 00:29 UTC, merged